# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Good')], default=0),
        ),
    ]
